CREATE DATABASE IF NOT EXISTS thegate;

USE thegate;

SET autocommit=0;
START TRANSACTION;

DROP TABLE IF EXISTS OrderProduct;
DROP TABLE IF EXISTS ProductShipment;
DROP TABLE IF EXISTS Product;
DROP TABLE IF EXISTS Shipment;
DROP TABLE IF EXISTS ShipmentMethod;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS OrderStatus;
DROP TABLE IF EXISTS OrderType;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS UserType;

CREATE TABLE UserType(
TypeId INT PRIMARY KEY NOT NULL,
Name VARCHAR(30) NOT NULL
);

CREATE TABLE User(
UserId BIGINT PRIMARY KEY AUTO_INCREMENT,
Type INT NOT NULL,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
Address VARCHAR(256),
Email varchar(128),
Password CHAR(64) NOT NULL,
FOREIGN KEY (Type) REFERENCES UserType(TypeId)
);

CREATE TABLE OrderType(
TypeId INT PRIMARY KEY NOT NULL
-- Name VARCHAR(64) NOT NULL
);

CREATE TABLE OrderStatus(
OrderStatusId INT PRIMARY KEY NOT NULL,
Name VARCHAR(64) NOT NULL
);

CREATE TABLE Orders(
OrderId BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
UserId BIGINT NOT NULL,
OrderType INT NOT NULL,
OrderStatus INT NOT NULL,
FOREIGN KEY (UserId) REFERENCES User(UserId),
FOREIGN KEY (OrderStatus) REFERENCES OrderStatus(OrderstatusId),
FOREIGN KEY (OrderType) REFERENCES OrderType(TypeId)
);

CREATE TABLE ShipmentMethod(
MethodId INT PRIMARY KEY NOT NULL,
Name VARCHAR(64)
);

CREATE TABLE Shipment(
ShipmentId BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
OrderId BIGINT NOT NULL,
ShipmentMethod INT NOT NULL,
ShipmentDate DATETIME NOT NULL,
FOREIGN KEY (OrderId) REFERENCES Orders(OrderId),
FOREIGN KEY (ShipmentMethod) REFERENCES ShipmentMethod(MethodId)
);

CREATE TABLE Product(
ProductId BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
Name VARCHAR(256) NOT NULL,
Description TEXT,
Quantity INT,
Price REAL
);

CREATE TABLE ProductShipment(
ProductId BIGINT NOT NULL,
ShipmentId BIGINT NOT NULL,
Quantity INT,
PRIMARY KEY (ProductId, ShipmentId),
FOREIGN KEY (ProductId) REFERENCES Product(ProductId),
FOREIGN KEY (ShipmentId) REFERENCES Shipment(ShipmentId)
);

CREATE TABLE OrderProduct(
OrderId BIGINT NOT NULL,
ProductId BIGINT NOT NULL,
Quantity INT,
PRIMARY KEY (OrderId, ProductId),
FOREIGN KEY (OrderId) REFERENCES Orders(OrderId),
FOREIGN KEY (ProductId) REFERENCES Product(ProductId)
);

COMMIT;
